mappings:
  - name: etl
    doc_type: subject
    type: aggregator
    root: subject
    _props:
      - submitter_id
      - project_id
    _flatten_props:
      - path: virus_infections
        _props:
          - virus_type
      - path: demographics
        _props:
          - gender
          - race
          - ethnicity
          - vital_status
          - year_of_birth
    _aggregated_props:
      - name: _follow_ups_count
        path: follow_ups
        fn: count
      - name: _summary_drug_uses_count
        path: follow_ups.summary_drug_uses
        fn: count
      - name: _summary_lab_results_on_follow_up_count
        path: follow_ups.summary_lab_results
        fn: count
      - name: _samples_count
        path: samples
        fn: count
      - name: _aliquots_count
        leaf: aliquot
        path: samples.aliquots
        fn: count
      - name: _summary_lab_results_on_sample_count
        path: samples.summary_lab_results
        fn: count
      - name: _mRNA_microarrays_count
        path: samples.aliquots.mrna_microarrays
        fn: count
      - name: _miRNA_microarrays_count
        path: samples.aliquots.mirna_microarrays
        fn: count
      - name: _lipid_mass_spectrometries_count
        path: samples.aliquots.lipid_mass_spectrometries
        fn: count
      - name: _protein_mass_spectrometries_count
        path: samples.aliquots.protein_mass_spectrometries
        fn: count
      - name: _metabolite_mass_spectrometries_count
        path: samples.aliquots.metabolite_mass_spectrometries
        fn: count
  - name: file
    doc_type: file
    type: collector
    root: None
    _props:
      - object_id
      - md5sum
      - file_name
      - file_size
      - state
    _injecting_props:
      subject:
        _props:
          - id
          - project_id
    _target_nodes:
      - name: mutation_panel
        path: subjects
      - name: bgm_simulation
        path: mutation_panels.subjects
      - name: mrna_microarray
        path: aliquots.samples.subjects
      - name: mirna_microarray
        path: aliquots.samples.subjects
      - name: lipid_mass_spectrometry
        path: aliquots.samples.subjects
      - name: protein_mass_spectrometry
        path: aliquots.samples.subjects
      - name: metabolite_mass_spectrometry
        path: aliquots.samples.subjects
      - name: submitted_copy_number
        path: aliquots.samples.subjects
      - name: submitted_methylation
        path: aliquots.samples.subjects
      - name: submitted_aligned_reads
        path: read_groups.aliquots.samples.subjects
      - name: submitted_unaligned_reads
        path: read_groups.aliquots.samples.subjects
      - name: submitted_genomic_profile
        path: read_groups.aliquots.samples.subjects
      - name: submitted_somatic_mutation
        path: read_groups.aliquots.samples.subjects

